services:
  db:
    image: mariadb
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root-password

  pma:
    image: phpmyadmin
    ports:
      - "3307:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root-password
